version: '3'

services:
    develop:
        build: https://github.com/softprops/lambda-rust.git#e6137ddbac36d104236407eb537c6c03a16a30fa
        environment:
            - PACKAGE=false
        volumes:
            - ${PWD}:/code
            - ${HOME}/.cargo/registry:/cargo/registry
            - ${HOME}/.cargo/git:/cargo/git
