version: '3'

services:
    foo:
        build: https://github.com/softprops/lambda-rust.git#e6137ddbac36d104236407eb537c6c03a16a30fa
        volumes:
            - /home/kuwata0037/tmp/rust-sam-lay:/code
            - ${HOME}/.cargo/registry:/cargo/registry
            - ${HOME}/.cargo/git:/cargo/git
